version: '3'
services:
    db:
        image: mariadb:11.2.2-jammy
        container_name: lt-cc-db
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
        depends_on:
            - app
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - default

    app:
        image: nginx:latest
        container_name: lt-cc-app
        ports:
            - '8080:80'
        networks:
            - default
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        build: docker/php-fpm
        networks:
            - default
        volumes:
            - .:/var/www/html
