version: '3'
services:
    db:
        image: mariadb:latest
        container_name: lt-cc-db
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: lt-cc-db-app
        depends_on:
            - app
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - default

    app:
        image: nginx:latest
        container_name: lt-cc-app
        ports:
            - '8080:80'
        networks:
            - default
        volumes:
            - .:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        image: php:8-fpm
        networks:
            - default
        volumes:
            - .:/var/www/html
